AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaS3Bucket:
    Type: String
    Description: "S3 bucket where the Lambda function package is stored"

Resources:
  GolfScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GolfScores
      AttributeDefinitions:
        - AttributeName: player
          AttributeType: S
        - AttributeName: hole
          AttributeType: N
      KeySchema:
        - AttributeName: player
          KeyType: HASH
        - AttributeName: hole
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  GolfTrackerLambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "golf-tracker-lambda-${AWS::AccountId}-${AWS::Region}"

  GolfTrackerWebS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "golf-tracker-web-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # GolfTrackerWebS3BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref GolfTrackerWebS3Bucket
  #     PolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal: "*"
  #           Action: "s3:GetObject"
  #           Resource: !Sub "arn:aws:s3:::${GolfTrackerWebS3Bucket}/*"

  GolfTrackerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: GolfTrackerLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt GolfScoresTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  GolfTrackerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GolfTrackerFunction
      Runtime: python3.8
      Handler: index.lambda_handler
      Role: !GetAtt GolfTrackerLambdaRole.Arn
      Code:
        S3Bucket:  !Ref LambdaS3Bucket
        S3Key: lambda_function.zip
      Environment:
        Variables:
          DYNAMODB_TABLE: GolfScores

  GolfApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GolfScoreAPI

  GolfApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref GolfApiGateway
      ParentId: !GetAtt GolfApiGateway.RootResourceId
      PathPart: score

  GolfApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref GolfApiGateway
      ResourceId: !Ref GolfApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GolfTrackerLambda.Arn}/invocations"

  GolfApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GolfTrackerLambda
      Principal: apigateway.amazonaws.com

Outputs:
  GolfTrackerLambdaS3BucketName:
    Description: "S3 bucket for storing Lambda function code"
    Value: !Ref GolfTrackerLambdaS3Bucket
  GolfTrackerWebS3BucketName:
    Description: "S3 bucket for hosting the golf tracker website"
    Value: !Ref GolfTrackerWebS3Bucket
  GolfApiGatewayInvokeURL:
    Description: "Invoke URL for API Gateway"
    Value: !Sub "https://${GolfApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/score"
